### ISSUE TITLE
builtin print function not found when called inside a module

### ISSUE THREAD

**Issue by 0verse** [mini-rose/coffee#12] opened 2023-02-16 18:24 UTC
I have a module named strinc.ff which cantains:
```
fn print_str(s: str) {
    print(s)
}
```
The hello.ff file contains:
```
use "strinc"

fn main() {
    _str: str = "hello world"
    print_str(_str)
}
```
I get this error message while compiling:

> özcü@özcül ~/çizeylemcil/coffee # nxg -M -o hello hello.ff 
> 
> error in strinc.ff:
> 
> 1	    print(s)
> 	             ^~~~~ no function named `print` found
>

**Comment by bellrise** [comment] 2023-02-16 20:22
I know what the problem is, I should find some time tommorow to fix it.

**Comment by bellrise** [comment] 2023-02-17 09:23
Fixed as of e0affe7.

**Closed by bellrise** 2023-02-17 09:23 UTC

**Comment by 0verse** [comment] 2023-02-17 11:57
thanks a lot :)
